name: build LXD image
on:
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: prepare LXD
        run: |
          sudo snap install lxd
          sudo lxd init --auto
      - uses: actions/checkout@v2
      - name: apply LXD patch
        run: |
          patch -p1 < lxd.patch
      - name: packer validate packer.json
        uses: operatehappy/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: images/linux/ubuntu2004.json
      - name: packer build packer.json
        uses: operatehappy/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: images/linux/ubuntu2004.json
      - uses: mxschmitt/action-tmate@v3
        if: ${{ always() }}
