name: build LXD image
on:
  push:
    branches:
      - "**"
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: bonddim/action-lxd@v1
      - uses: actions/checkout@v2
      - name: apply LXD patch
        run: |
          patch -p1 < lxd.patch
      - name: packer validate packer.json
        uses: docker://hashicorp/packer:1.7.0
        with:
          args: validate images/linux/ubuntu2004.json
      - name: packer build packer.json
        uses: docker://hashicorp/packer:1.4.3
        with:
          args: build images/linux/ubuntu2004.json
        #- uses: mxschmitt/action-tmate@v3
