name: build LXD image
on:
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: prepare LXD
        run: |
          sudo snap install lxd
          sudo lxd init --auto
      - name: prepare packer
        run: |
          sudo apt-get install -y wget unzip
          sudo curl -L -O https://releases.hashicorp.com/packer/1.7.0/packer_1.7.0_linux_amd64.zip
          sudo unzip packer_1.7.0_linux_amd64.zip
          sudo mv ./packer /tmp/packer
      - uses: actions/checkout@v2
      - name: apply LXD patch
        run: |
          patch -p1 < lxd.patch
      - name: packer validate packer.json
        run: |
          /tmp/packer validate -syntax-only images/linux/ubuntu2004.json
      - name: packer build packer.json
        run: |
          /tmp/packer build -color=false -on-error=abort images/linux/ubuntu2004.json
      - uses: mxschmitt/action-tmate@v3
        if: ${{ always() }}
