name: nightly update
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: whywaita/setup-lxd@v1
      - uses: hashicorp-contrib/setup-packer@v1
      - uses: actions/checkout@v2
      - name: Delete unused file
        run: |
          sudo rm -rf /opt/hostedtoolcache
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/*
          sudo rm -rf /var/lib/docker/*

          # ignore /usr/share/dpkg
          ls /usr/share/ | grep -v dpkg | xargs -I%% sudo rm -rf /usr/share/%%
      - name: Pull from upstream
        run: |
          git remote add upstream https://github.com/actions/virtual-environments/
          git pull upstream main
      - name: Apply LXD patch
        run: |
          patch -p1 < lxd.patch


      - name: packer validate packer.json
        run: |
          packer validate -syntax-only images/linux/ubuntu2004.json
      - name: packer build packer.json
        run: |
          packer build -color=false -on-error=abort images/linux/ubuntu2004.json
        env:
          PACKER_LOG: 1
      - name: Export image
        run: |
          mkdir -p _output
          lxc image export packer-lxd ./_output

      - name: Apply to main
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          git push origin main
      - name: Notify status
        uses: lazy-actions/slatify@master
        if: always()
        with:
          job_name: '*build virtual-environments-lxd*'
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          token: ${{ secrets.GITHUB_TOKEN }}
